# niri-sidebar configuration

[geometry]
# Width of the sidebar in pixels
width = 400
# Height of the sidebar windows
height = 335
# Gap between windows in the stack
gap = 10

[margins]
# Margins are default to 0 if left out
# Space from the top of the screen
top = 50
# Space from the right edge of the screen
right = 10
# Space from the left edge of the screen
left = 10
# Space from the bottom of the screen
bottom = 10 

[interaction]
# Where to put the sidebar, can be "left", "right", "top" or "bottom"
# Defaults to "right"
position = "right"
# Width of windows when sidebar is hidden in pixels
peek = 10
# Pixels visible when sidebar is hidden but window is focused
# Set this equal to peek to disable this feature
# Set this equal to width + right margin to make focused windows fully "unhide"
# Optional and defaults to peek if omitted
focus_peek = 50
# Whether the sidebar should follow if you switch workspaces
sticky = false
# Automatically focus the appropriate layer when toggling visibility
# On unhide: focuses the floating layer. On hide: focuses the tiling layer.
auto_focus_layer = false

# Example window rule
# all fields are optional if not given a default from other configs will be used
# [[window_rule]]
# app_id = "firefox"  # if not set will match all app_id's
# title = "^Picture-in-Picture$"  # if not set will match no matter the title
# width = 700
# height = 400
# focus_peek = 710
# peek = 10
# auto_add = true  # defaults to false
